### PR TITLE
add isPlayerFinished

### PR DESCRIPTION
**Pull request by hideakitai**
I tried to add `bool isPlayerFinished(PlayerID)` to get if the player has finished playing fifo buffer data, because I wanted to detect if the Player0/1 has finished playing (to repeat sounds). I also tried:

- derive from AudioClass -> couldn't handle CMN_SimpleFifoHandle from derived class (private member)
- detect from audio attention callback -> could'nt detect which player has finished playing (FIFO buffer underflow, Attention Code = 1, Attention Sub Code = 5)

If you have better solution for this problem, let me know please.
Thank you.

### CODE REVIEW

**Comment by hideakitai** [comment]
I got it, the problem is `AudioAttentionCb` is set only for `AS_CreateAudioManager`. Another solution is to set callbacks each for two `AS_CreatePlayerMulti` in `AudioClass::begin_player`.

**Comment by hideakitai** [comment]
Thank you for the reply. I understood it, that's good, I think I can realize what I want.
Please close this PR if you have implemented, thank you.

**Comment by Shunichi-K** [comment]
Sorry for late information.

This extension has been reflected in release version v1.3.0.

We added `player_id` as `submodule_id` in `AudioResultHeader/ErrorResponseParam/ErrorAttentionParam` in Spresense SDK side API.
In Arduino environment, we can check `player_id` from `ErrorAttentionParam` with `attentionCallback`.

If you have any comment for this interface,
please feel free to let us know.

Best regards,
Spresense developer team.

**Comment by SPRESENSE** [comment]
Sorry for late information.

This extension has been reflected in release version v1.3.0.

We added `player_id` as `submodule_id` in `AudioResultHeader/ErrorResponseParam/ErrorAttentionParam` in Spresense SDK side API.
In Arduino environment, we can check `player_id` from `ErrorAttentionParam` with `attentionCallback`.

If you have any comment for this interface,
please feel free to let us know.

Best regards,
Spresense developer team.

**Comment by hideakitai** [comment]
I'm sorry for late reply, I've checked it.
I thought I can get sub_module_id in `audio_attention_cb`, but I couldn't...
Because `audio_attention_cb` is called if theAudio->stopPlayer() is called... (I think)
How can I re-start sound by attentionCallback?

I want to:
- check if player is finished by `attentionCallback`
- stopPlayer (but `attentionCallback` may be called after this `stopPlayer`)
- initPlayer
- play audio

**Comment by TomonobuHayakawa** [comment]
With the Hi-Level API at that time, in the case of dualplay, if one stopped, the other could underflow.
Perhaps it is seems to happen this probrem.

The latest v1.5.0 resolves this problem.
Also, it does not occur if you use Object Layer.

Please try again with the latest version?

Best regards,
Spresense developer team.

**Comment by SPRESENSE** [comment]
Perhaps it seems known issue.
In the Hi-Level API of old Spresense SDK version, in the case of dualplay, if one stopped, the other could underflow.

The latest v1.5.0 resolves this problem.
Also, it does not occur if you use Object Layer APIs.

Could you try again with the latest version?

Best regards,
Spresense developer team.

**Comment by hideakitai** [comment]
I've tried it and Object Layer API worked best for me.
Thanks!

**Pull request closed without merging**
